# -*- coding: utf-8 -*-
"""Tefe29.08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1obz8rcUmHb9u0nTjZYex-qdKw4NiTZMS
"""

import numpy as np
import matplotlib.pyplot as plt

a0 = 10.0
sa = 0.2
b0 = 5.0
sb = 0.2

def Z(a,b):
  return 2*(a**2)*b

N = 10000
Zs_a = []

for i in range(N):
  a = a0 + sa*np.random.randn()
  Zs_a.append( Z(a,b) )

sz_a = np.std( Zs_a, ddof=1 )
print(f'sz_a = {sz_a:.2f}')

Zs_b = []
for i in range(N):
  b = b0 + sb*np.random.randn()
  Zs_b.append( Z(a,b) )

sz_b = np.std( Zs_b, ddof=1 )
print(f'sz_b = {sz_b:.2f}')

sZ = np.sqrt(sz_a**2 +sz_b**2)
print(f'sZ = {sZ:.2f}')

def simulaExpAleaSist(N,x0 = 50.0,sA = 2.0,sS = 0.5):
  erroSist = sS*np.random.randn()
  x = []
  for i in range(N):
    erroAleat = sA*np.random.randn()
    xi = x0 + erroSist + erroAleat
    x.append(xi)
  return x

xALL = []
plt.figure()
for i in range(20):
  xALL.append( simulaExpAleaSist( N=25, sA=1, sS=5 ) )
plt.plot( np.hstack(np.array(xALL)), '.' )
plt.show()

nREP = 10_000
sA = 2.0
sS = 0.3
n = 25
xMs = []
for i in range(nREP):
  x = simulaExpAleaSist( N=n, sA=sA, sS=sS )
  xMs.append( np.mean(x) )

sf = np.std( xMs, ddof=1 )
print( f's_f = {sf:.5f}')