# -*- coding: utf-8 -*-
"""Tefe15.09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fEbF9vYygDn-YbivnloEa36f8oEodqE0
"""

import numpy as np
import matplotlib.pyplot as plt

def geraDadosMetodoExclusao( N=1, f=lambda x:1-abs(x), xI=-1, xS=+1, yMax=1 ):
  x = []
  while( len(x)<N ):
    xc = np.random.rand()*(xS-xI) + xI
    yv = yMax * np.random.rand()
    if yv<=f(xc):
      x.append(xc)
  return x

N = 10_000
x = geraDadosMetodoExclusao( N )
print( 'xm = ', np.mean(x) )
print( 'sx = ', np.std(x, ddof=1))