# -*- coding: utf-8 -*-
"""Tefe19.09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13uKdfTsK7gEUYNls0nALSYXw9s5O6FI0
"""

import numpy as np
import matplotlib.pyplot as plt
import math

np.random.seed(12803112)

N = 10000
def geraDadosExclusao( N=10000, f=lambda x: (5/8)*(1-x**4), xI=-1, xS=+1, yMax=0.625):
  x = []
  while( len(x)<N ):
    xc = np.random.rand()*(xS-xI) + xI
    yv = yMax * np.random.rand()
    if yv<=f(xc):
      x.append(xc)
  return x

def geraDadosExclusao2( N=10000, f=lambda x:0.5*np.cos(x), xI=-np.pi/2, xS=np.pi/2, yMax=0.5):
  y = []
  while( len(y)<N ):
    xc = np.random.rand()*(xS-xI) + xI
    yv = yMax * np.random.rand()
    if yv<=f(xc):
      y.append(xc)
  return y

def dados(k):
  media = np.mean(k)
  desvio = np.std(k,ddof=1)
  print (f'{media:.5f}, {desvio:.5f}')
 
  contamais = 0

  xmais = media + desvio
  xmenos = media - desvio

  for j in range(1,4,1):
    for i in range (len(k)):
      if (k[i] >= j*xmenos and k[i] <= j*xmais):
        contamais += 1
    print (contamais)
    contamais = 0



M = geraDadosExclusao(N)
plt.hist(M,30)
plt.show()
dados1 = dados(M)

ya =geraDadosExclusao2()

plt.hist(ya,30)
plt.show()
dados2 = dados(ya)