# -*- coding: utf-8 -*-
"""Tefe17.10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RTU_8xgxAqF51GwFw9GQTGymw-i-zgUu
"""

import numpy as np
np.random.seed(12803112)

M = 10_000
x0 =15
sx = 2
y0 = 40
sy = 3

x = x0+np.random.randn(M)*sx
y = y0+np.random.randn(M)*sy
w = lambda x,y : x*y

wm = w(x,y)
print(f'wm = {np.mean(wm):.2f}; sw = {np.std(wm,ddof=1):.2f}\n')

#######################################################################
x = x0+np.random.randn(M)*sx
y = y0+np.random.randn(M,2)*sy
ym = np.mean(y,axis=1)
wb2=w(x,ym)

print(f'wb2 = {np.mean(wb2):.2f}; swb2 = {np.std(wb2,ddof=1):.2f}\n')

#######################################################################
x = x0+np.random.randn(M,2)*sx
y = y0+np.random.randn(M)*sy
xm = np.mean(x,axis=1)
wb1=w(xm,y)

print(f'wb1 = {np.mean(wb1):.2f}; swb1 = {np.std(wb1,ddof=1):.2f}\n')

########################################################################
Nx = [1,2,3,4,5,6,7,8,9,10]
Ny = [10,9,8,7,6,5,4,3,2,1]

for i in range(len(Nx)):
  x = x0+np.random.randn(M,Nx[i])*sx
  y = y0+np.random.randn(M,Ny[i])*sy
  xm = np.mean(x,axis=1)
  ym = np.mean(y,axis=1)
  wc=w(xm,ym)
  print(f'wc {i+1} = {np.mean(wc):.2f}; swc {i+1} = {np.std(wc,ddof=1):.2f}')

